INSERT INTO raca (tipo, descricao) VALUES (2,'Agapórnis');
INSERT INTO raca (tipo, descricao) VALUES (2,'Arara Vermelha de Asa Verde');
INSERT INTO raca (tipo, descricao) VALUES (2,'Azulão');
INSERT INTO raca (tipo, descricao) VALUES (2,'Bavette');
INSERT INTO raca (tipo, descricao) VALUES (2,'Bicudo');
INSERT INTO raca (tipo, descricao) VALUES (2,'Caboclinho');
INSERT INTO raca (tipo, descricao) VALUES (2,'Cacatua');
INSERT INTO raca (tipo, descricao) VALUES (2,'Calafate');
INSERT INTO raca (tipo, descricao) VALUES (2,'Calopsita');
INSERT INTO raca (tipo, descricao) VALUES (2,'Canário da Terra');
INSERT INTO raca (tipo, descricao) VALUES (2,'Canário de Harz');
INSERT INTO raca (tipo, descricao) VALUES (2,'Cardeal da Virgínia');
INSERT INTO raca (tipo, descricao) VALUES (2,'Coleiro');
INSERT INTO raca (tipo, descricao) VALUES (2,'Cordonbleu');
INSERT INTO raca (tipo, descricao) VALUES (2,'Coruja');
INSERT INTO raca (tipo, descricao) VALUES (2,'Curió');
INSERT INTO raca (tipo, descricao) VALUES (2,'Diamante de Gould');
INSERT INTO raca (tipo, descricao) VALUES (2,'Esplêndido');
INSERT INTO raca (tipo, descricao) VALUES (2,'Granatina');
INSERT INTO raca (tipo, descricao) VALUES (2,'Lóris');
INSERT INTO raca (tipo, descricao) VALUES (2,'Mainá');
INSERT INTO raca (tipo, descricao) VALUES (2,'Mandarim');
INSERT INTO raca (tipo, descricao) VALUES (2,'Manon');
INSERT INTO raca (tipo, descricao) VALUES (2,'Melro');
INSERT INTO raca (tipo, descricao) VALUES (2,'Modesto');
INSERT INTO raca (tipo, descricao) VALUES (2,'Papagaio');
INSERT INTO raca (tipo, descricao) VALUES (2,'Papagaio Cinzento Africano');
INSERT INTO raca (tipo, descricao) VALUES (2,'Pardal Doméstico');
INSERT INTO raca (tipo, descricao) VALUES (2,'Patativa');
INSERT INTO raca (tipo, descricao) VALUES (2,'Periquito Australiano');
INSERT INTO raca (tipo, descricao) VALUES (2,'Periquito Maracanã');
INSERT INTO raca (tipo, descricao) VALUES (2,'Pintassilgo da Venezuela');
INSERT INTO raca (tipo, descricao) VALUES (2,'Rola Diamante');
INSERT INTO raca (tipo, descricao) VALUES (2,'Rolinha Fogo-Pagou');
INSERT INTO raca (tipo, descricao) VALUES (2,'Rouxinol de Pequim');
INSERT INTO raca (tipo, descricao) VALUES (2,'Sabiá Laranjeira');
INSERT INTO raca (tipo, descricao) VALUES (2,'Sairá-de-Lenço');
INSERT INTO raca (tipo, descricao) VALUES (2,'Starfinsh');
INSERT INTO raca (tipo, descricao) VALUES (2,'Tangará-Dançarino');
INSERT INTO raca (tipo, descricao) VALUES (2,'Tarim');
INSERT INTO raca (tipo, descricao) VALUES (2,'Tico-Tico');
INSERT INTO raca (tipo, descricao) VALUES (2,'Trinca Ferro');
INSERT INTO raca (tipo, descricao) VALUES (2,'Tucano');
INSERT INTO raca (tipo, descricao) VALUES (2,'Tuim');
