CREATE TABLE cor(
  id tinyint(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome varchar(45) DEFAULT NULL,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;