INSERT INTO raca (tipo, descricao) VALUES (0,'Sem Raça Definida (SRD)');
INSERT INTO raca (tipo, descricao) VALUES (0,'Affenpinscher');
INSERT INTO raca (tipo, descricao) VALUES (0,'Affenpinscher ');
INSERT INTO raca (tipo, descricao) VALUES (0,'Afghan Hound');
INSERT INTO raca (tipo, descricao) VALUES (0,'Aidi');
INSERT INTO raca (tipo, descricao) VALUES (0,'Airedale Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Akita Inu');
INSERT INTO raca (tipo, descricao) VALUES (0,'American Bully');
INSERT INTO raca (tipo, descricao) VALUES (0,'American Staffordshire Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Australian Cattle Dog');
INSERT INTO raca (tipo, descricao) VALUES (0,'Australian Shepherd');
INSERT INTO raca (tipo, descricao) VALUES (0,'Australian Silky Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Azawakh');
INSERT INTO raca (tipo, descricao) VALUES (0,'Barbet');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basenji');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basset Alpino');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basset Artesiano Normando');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basset Azul da Gasconha');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basset de Vestfália');
INSERT INTO raca (tipo, descricao) VALUES (0,'Basset Hound');
INSERT INTO raca (tipo, descricao) VALUES (0,'Beagle');
INSERT INTO raca (tipo, descricao) VALUES (0,'Beagle Harrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bearded Collie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bedlington Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bernese Mountain Dog');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bichon Bolonhês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bichon Frisé');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bichon Havanês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Billy');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bloodhound');
INSERT INTO raca (tipo, descricao) VALUES (0,'Boiadeiro de Appenzel');
INSERT INTO raca (tipo, descricao) VALUES (0,'Boiadeiro de Entlebuch');
INSERT INTO raca (tipo, descricao) VALUES (0,'Boiadeiro de Flandres');
INSERT INTO raca (tipo, descricao) VALUES (0,'Border Collie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Border Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Borzói');
INSERT INTO raca (tipo, descricao) VALUES (0,'Boston Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Boxer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Alemão de Pêlo Curto');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Alemão de Pêlo Duro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Alemão de Pêlo Longo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Austríaco de Pelo Liso');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco de Auvergne');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco de Bourbon');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco de Burgos');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco de Saint-germain');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Dinamarquês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco do Ariège');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Eslovaco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Francês (Gascão E Pirenéus)');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Húngaro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Italiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Polonês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Braco Tirolês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Broholmer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Buhund Norueguês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Buldogue inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bull Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bulldog');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bulldog Francês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Bullmastiff');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cairn Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cane Corso');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão D`água Português');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão da Eurásia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão da Groenlândia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão da Islândia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão da Serra da Estrela');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Artois');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Bestiar');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Caça Ao Cervo Sueco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Canãa');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Castro Laboreiro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Crista Chinês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cao de Guarda Holandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Lontra');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Pista de Sangue da Baviera');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão de Urso da Carélia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão do Ariège');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão do Faraó');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Dos Pirenéus');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão D`água Americano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão D`água Espanhol');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão D`água Frison');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão D`água Irlandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Finlandês da Lapônia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Lobo Checoslovaco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Lobo de Saarloos');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Norueguês de Macareux');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cão Tailandês de Crista Dorsal');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cavalier King Charles Spaniel');
INSERT INTO raca (tipo, descricao) VALUES (0,'Chihuahua');
INSERT INTO raca (tipo, descricao) VALUES (0,'Chow Chow');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cirneco do Etna');
INSERT INTO raca (tipo, descricao) VALUES (0,'Clumber');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cocker Spaniel Americano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Cocker Spaniel Inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Collie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Coonhound Preto E Castanho');
INSERT INTO raca (tipo, descricao) VALUES (0,'Coton de Tulear');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dachshund');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dachshund Pêlo Duro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dálmata');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dandie Dinmont Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Doberman');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dogo Argentino');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dogue Alemão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dogue de Bordeaux');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dogue do Tibete');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dogue Maiorquino');
INSERT INTO raca (tipo, descricao) VALUES (0,'Drever');
INSERT INTO raca (tipo, descricao) VALUES (0,'Dunker Norueguês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Elkhoud Norueguês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Field Spaniel');
INSERT INTO raca (tipo, descricao) VALUES (0,'Fila Brasileiro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Fox Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Foxhound Americano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Foxhound Inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Francês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Fulvo da Bretanha de Pelô Duro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Galgo Escocês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Galgo Espanhol');
INSERT INTO raca (tipo, descricao) VALUES (0,'Galgo Húngaro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Galgo Polonês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Gascão Saintongeois');
INSERT INTO raca (tipo, descricao) VALUES (0,'Golden Retriever');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grande Boiadeiro Suíço');
INSERT INTO raca (tipo, descricao) VALUES (0,'Greyhound');
INSERT INTO raca (tipo, descricao) VALUES (0,'Griffon de Bruxelas');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo Belga,');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo Bruxelense');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo da Vendéia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo de Aponte de Pêlo Duro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo de Caça Checo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Grifo Nivernais');
INSERT INTO raca (tipo, descricao) VALUES (0,'Halden Stovare');
INSERT INTO raca (tipo, descricao) VALUES (0,'Hamilton Stovare');
INSERT INTO raca (tipo, descricao) VALUES (0,'Hanover');
INSERT INTO raca (tipo, descricao) VALUES (0,'Harrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Hokkaïdo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Hovawart');
INSERT INTO raca (tipo, descricao) VALUES (0,'Husky Siberiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Irish Glen Of Imaal Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Irish Soft Coated Wheaten Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Irish Wolfhound');
INSERT INTO raca (tipo, descricao) VALUES (0,'Jack Russel Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kai');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kelpie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kerry Blue Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'King Charles Spaniel');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kishu');
INSERT INTO raca (tipo, descricao) VALUES (0,'Komondor');
INSERT INTO raca (tipo, descricao) VALUES (0,'Korea Jindo Dog');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kromfohrländer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Kuvasz');
INSERT INTO raca (tipo, descricao) VALUES (0,'Labrador Retriever');
INSERT INTO raca (tipo, descricao) VALUES (0,'Lagotto Romagnolo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Laika');
INSERT INTO raca (tipo, descricao) VALUES (0,'Lakeland Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Landseer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Leonberger');
INSERT INTO raca (tipo, descricao) VALUES (0,'Lhasa Apso');
INSERT INTO raca (tipo, descricao) VALUES (0,'Malamute do Alasca');
INSERT INTO raca (tipo, descricao) VALUES (0,'Maltês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Manchester Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Mastiff');
INSERT INTO raca (tipo, descricao) VALUES (0,'Mastim Dos Pireneus');
INSERT INTO raca (tipo, descricao) VALUES (0,'Mastim Espanhol');
INSERT INTO raca (tipo, descricao) VALUES (0,'Mastim Napolitano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Mudi');
INSERT INTO raca (tipo, descricao) VALUES (0,'Norfolk Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Norwich Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Old English Sheepdog');
INSERT INTO raca (tipo, descricao) VALUES (0,'Papillon Borboleta E Falena');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Alemão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Australiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Belga Groenendael');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Belga Malinois');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Belga Tervuren');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Bergamo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor branco suíço');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Catalão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Croata');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor da Anatólia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor da Ásia Central');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor da Picardia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor da Rússia Meridional');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor de Beauce');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor de Brie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor de Shetland');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor do Cáucaso');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Dos Pireneus');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Finlandês da Lapônia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Holandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Iugoslavo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Maremano Abruzzese');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Montanhês de Krast');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Polonês de Planície');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Polonês de Podhal');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pastor Português da Serra de Aires');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pelado Mexicano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pelado Peruano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pequeno Brabançon');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pequeno Cão Holandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pequeno Cão Leão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pequeno Galgo Italiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pequinês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Perdigueiro Alemão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Perdigueiro Português');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pinscher');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pinscher Austríaco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pitbull');
INSERT INTO raca (tipo, descricao) VALUES (0,'Podengo Ibicenco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Podengo Português');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pointer inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Poitevin');
INSERT INTO raca (tipo, descricao) VALUES (0,'Poodle');
INSERT INTO raca (tipo, descricao) VALUES (0,'Porcelana');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pudelpointer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pug');
INSERT INTO raca (tipo, descricao) VALUES (0,'Puli');
INSERT INTO raca (tipo, descricao) VALUES (0,'Pumi');
INSERT INTO raca (tipo, descricao) VALUES (0,'Rafeiro do Alentejo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Retriever da Baía de Chesapeake');
INSERT INTO raca (tipo, descricao) VALUES (0,'Retriever da Nova Escócia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Retriever de Pêlo Liso');
INSERT INTO raca (tipo, descricao) VALUES (0,'Retriever de Pêlo Ondulado');
INSERT INTO raca (tipo, descricao) VALUES (0,'Rodhesian Ridgeback ');
INSERT INTO raca (tipo, descricao) VALUES (0,'Rottweiler');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Alemão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Anglo Francês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo da Istria');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo da Transilvânia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo de Hygen');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo de Posavatz');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Eslovaco');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Espanhol');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Finlandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Italiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Iuguslavo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sabujo Suiço');
INSERT INTO raca (tipo, descricao) VALUES (0,'Saluki');
INSERT INTO raca (tipo, descricao) VALUES (0,'Samoieda');
INSERT INTO raca (tipo, descricao) VALUES (0,'São Bernardo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Schapendoes');
INSERT INTO raca (tipo, descricao) VALUES (0,'Schiller Stovare');
INSERT INTO raca (tipo, descricao) VALUES (0,'Schipperke');
INSERT INTO raca (tipo, descricao) VALUES (0,'Schnauzer');
INSERT INTO raca (tipo, descricao) VALUES (0,'Scottish Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sealyham Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Seter Gordon');
INSERT INTO raca (tipo, descricao) VALUES (0,'Seter Inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Setter Irlandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'SharPei');
INSERT INTO raca (tipo, descricao) VALUES (0,'Shiba');
INSERT INTO raca (tipo, descricao) VALUES (0,'Shih Tzu');
INSERT INTO raca (tipo, descricao) VALUES (0,'Skye Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sloughi');
INSERT INTO raca (tipo, descricao) VALUES (0,'Slovensky Cuvac');
INSERT INTO raca (tipo, descricao) VALUES (0,'Smäland Stovare');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Azul da Picardia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Bretão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel da Picardia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel de Munster');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel de Pont-audemar');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Francês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Japonês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Perdigueiro de Drenthe');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spaniel Tibetano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spinone Italiano de Pêlo Duro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz Alemão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz Alemão Anão');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz da Lapônia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz de Norboten');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz Dos Visigodos');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz Finlandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Spitz Japonês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Springer Spaniel Gaulês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Springer Spaniel Inglês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Stabyhoun');
INSERT INTO raca (tipo, descricao) VALUES (0,'Staffordshire Bull Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Sussex Spanie');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terra Nova');
INSERT INTO raca (tipo, descricao) VALUES (0,'TerraNova');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Alemão de Caça');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Australiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Brasileiro');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Checo');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Irlandês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Japonês');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Miniatura Preto E Castanho');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Preto da Rússia');
INSERT INTO raca (tipo, descricao) VALUES (0,'Terrier Tibetano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Tosa');
INSERT INTO raca (tipo, descricao) VALUES (0,'Vulpino Italiano');
INSERT INTO raca (tipo, descricao) VALUES (0,'Weimaraner');
INSERT INTO raca (tipo, descricao) VALUES (0,'Welsh Corgi Cardigan E Pembroke');
INSERT INTO raca (tipo, descricao) VALUES (0,'Welsh Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'West Highland White Terrier');
INSERT INTO raca (tipo, descricao) VALUES (0,'Whippet');
INSERT INTO raca (tipo, descricao) VALUES (0,'Yorkshire Terrier');