INSERT INTO raca (tipo, descricao) VALUES (1,'Sem Raça Definida (SRD)');
INSERT INTO raca (tipo, descricao) VALUES (1,'Abissínio');
INSERT INTO raca (tipo, descricao) VALUES (1,'American Bobtail');
INSERT INTO raca (tipo, descricao) VALUES (1,'American Curl');
INSERT INTO raca (tipo, descricao) VALUES (1,'American Shorthair');
INSERT INTO raca (tipo, descricao) VALUES (1,'American Wirehair');
INSERT INTO raca (tipo, descricao) VALUES (1,'Angorá Turco');
INSERT INTO raca (tipo, descricao) VALUES (1,'Azul Russo');
INSERT INTO raca (tipo, descricao) VALUES (1,'Balinês');
INSERT INTO raca (tipo, descricao) VALUES (1,'Bengal');
INSERT INTO raca (tipo, descricao) VALUES (1,'Bombaim');
INSERT INTO raca (tipo, descricao) VALUES (1,'British Shorthair');
INSERT INTO raca (tipo, descricao) VALUES (1,'Burmês');
INSERT INTO raca (tipo, descricao) VALUES (1,'Burmila');
INSERT INTO raca (tipo, descricao) VALUES (1,'Califórnia Spangled');
INSERT INTO raca (tipo, descricao) VALUES (1,'Ceilão');
INSERT INTO raca (tipo, descricao) VALUES (1,'Chartreux');
INSERT INTO raca (tipo, descricao) VALUES (1,'Cornish Rex');
INSERT INTO raca (tipo, descricao) VALUES (1,'Cymric');
INSERT INTO raca (tipo, descricao) VALUES (1,'Devon Rex');
INSERT INTO raca (tipo, descricao) VALUES (1,'Europeu');
INSERT INTO raca (tipo, descricao) VALUES (1,'Exotic Shorthair');
INSERT INTO raca (tipo, descricao) VALUES (1,'Gato dos Bosques da Noruega');
INSERT INTO raca (tipo, descricao) VALUES (1,'German Rex');
INSERT INTO raca (tipo, descricao) VALUES (1,'Havana');
INSERT INTO raca (tipo, descricao) VALUES (1,'Japanese Bobtail');
INSERT INTO raca (tipo, descricao) VALUES (1,'Javanês');
INSERT INTO raca (tipo, descricao) VALUES (1,'Korat');
INSERT INTO raca (tipo, descricao) VALUES (1,'Laperm');
INSERT INTO raca (tipo, descricao) VALUES (1,'Lince doméstico');
INSERT INTO raca (tipo, descricao) VALUES (1,'Maine Coon');
INSERT INTO raca (tipo, descricao) VALUES (1,'Manx');
INSERT INTO raca (tipo, descricao) VALUES (1,'Mau Egípcio');
INSERT INTO raca (tipo, descricao) VALUES (1,'Munchkin');
INSERT INTO raca (tipo, descricao) VALUES (1,'Ocicat');
INSERT INTO raca (tipo, descricao) VALUES (1,'Ojos azules');
INSERT INTO raca (tipo, descricao) VALUES (1,'Oriental');
INSERT INTO raca (tipo, descricao) VALUES (1,'Persa');
INSERT INTO raca (tipo, descricao) VALUES (1,'Pixie Bob');
INSERT INTO raca (tipo, descricao) VALUES (1,'Ragdoll');
INSERT INTO raca (tipo, descricao) VALUES (1,'Sagrado da Birmânia');
INSERT INTO raca (tipo, descricao) VALUES (1,'Scottish Fold');
INSERT INTO raca (tipo, descricao) VALUES (1,'Selkirk Rex');
INSERT INTO raca (tipo, descricao) VALUES (1,'Siamês');
INSERT INTO raca (tipo, descricao) VALUES (1,'Siberiano');
INSERT INTO raca (tipo, descricao) VALUES (1,'Singapura');
INSERT INTO raca (tipo, descricao) VALUES (1,'Snowshoe');
INSERT INTO raca (tipo, descricao) VALUES (1,'Sokoke');
INSERT INTO raca (tipo, descricao) VALUES (1,'Somali');
INSERT INTO raca (tipo, descricao) VALUES (1,'Sphynx');
INSERT INTO raca (tipo, descricao) VALUES (1,'Tonquinês');
INSERT INTO raca (tipo, descricao) VALUES (1,'Turco do Lago de Van');
INSERT INTO raca (tipo, descricao) VALUES (1,'York Chocolate');