INSERT INTO raca (tipo, descricao) VALUES (4,'Abelhinha');
INSERT INTO raca (tipo, descricao) VALUES (4,'Acará Bandeira');
INSERT INTO raca (tipo, descricao) VALUES (4,'Acará Disco');
INSERT INTO raca (tipo, descricao) VALUES (4,'Acará Jóia');
INSERT INTO raca (tipo, descricao) VALUES (4,'Anthias-Dourado');
INSERT INTO raca (tipo, descricao) VALUES (4,'Baiacú Biocelatus');
INSERT INTO raca (tipo, descricao) VALUES (4,'Beijador');
INSERT INTO raca (tipo, descricao) VALUES (4,'Beta');
INSERT INTO raca (tipo, descricao) VALUES (4,'Bótia');
INSERT INTO raca (tipo, descricao) VALUES (4,'Bótia Palhaço');
INSERT INTO raca (tipo, descricao) VALUES (4,'Cardinal Bangai');
INSERT INTO raca (tipo, descricao) VALUES (4,'Carpa');
INSERT INTO raca (tipo, descricao) VALUES (4,'Cascudo');
INSERT INTO raca (tipo, descricao) VALUES (4,'Ciclídeo');
INSERT INTO raca (tipo, descricao) VALUES (4,'Clown Triggerfish');
INSERT INTO raca (tipo, descricao) VALUES (4,'Colisa Lália');
INSERT INTO raca (tipo, descricao) VALUES (4,'Coridora');
INSERT INTO raca (tipo, descricao) VALUES (4,'Dourado');
INSERT INTO raca (tipo, descricao) VALUES (4,'Espada');
INSERT INTO raca (tipo, descricao) VALUES (4,'Flame Angel');
INSERT INTO raca (tipo, descricao) VALUES (4,'Green Chromis');
INSERT INTO raca (tipo, descricao) VALUES (4,'Killie Lira Comum');
INSERT INTO raca (tipo, descricao) VALUES (4,'Kinguio');
INSERT INTO raca (tipo, descricao) VALUES (4,'Lebiste');
INSERT INTO raca (tipo, descricao) VALUES (4,'Limpa Vidro');
INSERT INTO raca (tipo, descricao) VALUES (4,'Mato Grosso');
INSERT INTO raca (tipo, descricao) VALUES (4,'Molinésia');
INSERT INTO raca (tipo, descricao) VALUES (4,'Neon Cardinal');
INSERT INTO raca (tipo, descricao) VALUES (4,'Oscar');
INSERT INTO raca (tipo, descricao) VALUES (4,'Paulistinha');
INSERT INTO raca (tipo, descricao) VALUES (4,'Peixe Anjo Rainha');
INSERT INTO raca (tipo, descricao) VALUES (4,'Peixe-Mandarim');
INSERT INTO raca (tipo, descricao) VALUES (4,'Pintado');
INSERT INTO raca (tipo, descricao) VALUES (4,'Pirara');
INSERT INTO raca (tipo, descricao) VALUES (4,'Plati');
INSERT INTO raca (tipo, descricao) VALUES (4,'Purple Firefish');
INSERT INTO raca (tipo, descricao) VALUES (4,'Tetra Negro');
INSERT INTO raca (tipo, descricao) VALUES (4,'Tubarão Bala');
