INSERT INTO uf (sigla,codigo,nome) VALUES ('AC',12,'Acre');
INSERT INTO uf (sigla,codigo,nome) VALUES ('AL',27,'Alagoas');
INSERT INTO uf (sigla,codigo,nome) VALUES ('AM',13,'Amazonas');
INSERT INTO uf (sigla,codigo,nome) VALUES ('AP',16,'Amapá');
INSERT INTO uf (sigla,codigo,nome) VALUES ('BA',29,'Bahia');
INSERT INTO uf (sigla,codigo,nome) VALUES ('CE',23,'Ceará');
INSERT INTO uf (sigla,codigo,nome) VALUES ('DF',53,'Distrito Federal');
INSERT INTO uf (sigla,codigo,nome) VALUES ('ES',32,'Espírito Santo');
INSERT INTO uf (sigla,codigo,nome) VALUES ('GO',52,'Goiás');
INSERT INTO uf (sigla,codigo,nome) VALUES ('MA',21,'Maranhăo');
INSERT INTO uf (sigla,codigo,nome) VALUES ('MG',31,'Minas Gerais');
INSERT INTO uf (sigla,codigo,nome) VALUES ('MS',50,'Mato Grosso Do Sul');
INSERT INTO uf (sigla,codigo,nome) VALUES ('MT',51,'Mato Grosso');
INSERT INTO uf (sigla,codigo,nome) VALUES ('PA',15,'Pará');
INSERT INTO uf (sigla,codigo,nome) VALUES ('PB',25,'Paraíba');
INSERT INTO uf (sigla,codigo,nome) VALUES ('PE',26,'Pernambuco');
INSERT INTO uf (sigla,codigo,nome) VALUES ('PI',22,'Piauí');
INSERT INTO uf (sigla,codigo,nome) VALUES ('PR',41,'Paraná');
INSERT INTO uf (sigla,codigo,nome) VALUES ('RJ',33,'Rio De Janeiro');
INSERT INTO uf (sigla,codigo,nome) VALUES ('RN',24,'Rio Grande Do Norte');
INSERT INTO uf (sigla,codigo,nome) VALUES ('RO',11,'Rondonia');
INSERT INTO uf (sigla,codigo,nome) VALUES ('RR',14,'Roraima');
INSERT INTO uf (sigla,codigo,nome) VALUES ('RS',43,'Rio Grande Do Sul');
INSERT INTO uf (sigla,codigo,nome) VALUES ('SC',42,'Santa Catarina');
INSERT INTO uf (sigla,codigo,nome) VALUES ('SE',28,'Sergipe');
INSERT INTO uf (sigla,codigo,nome) VALUES ('SP',35,'Săo Paulo');
INSERT INTO uf (sigla,codigo,nome) VALUES ('TO',17,'Tocantins');