CREATE TABLE IF NOT EXISTS
  `animal` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT(1)  NOT NULL DEFAULT '0' COMMENT 'CACHORRO, GATO, PASSARO, COELHO, PEIXE, REPTIL',
  `nome` VARCHAR(150) NOT NULL,
  `data_nascimento` DATE, 
  `sexo` TINYINT(1) NOT NULL DEFAULT '0', 
  `pelo` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'CURTO, LONGO' ,
  `cor` VARCHAR(255) NULL,
  `castrado` TINYINT(1) NOT NULL DEFAULT 0,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'INATIVO, ATIVO',  
  `cliente_id` INT(11) UNSIGNED NOT NULL,
  `raca_id` SMALLINT(6) NOT NULL,  
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_animal_cliente` FOREIGN KEY (`cliente_id`) REFERENCES `cliente` (`id`),
  CONSTRAINT `fk_animal_raca` FOREIGN KEY (`raca_id`) REFERENCES `raca` (`id`))
   ENGINE=InnoDB;