server:
  port: 9999

logging:
  level:
    org.springframework.web: DEBUG 
    org.springframework.security: DEBUG
      

spring:
  datasource:
    url: ${projeto.db.url}?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${projeto.db.usuario}
    password: ${projeto.db.senha}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      idle-timeout: 600000 
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ????????????????????
    password: ????????????????????
    properties:
      mail.smtp.auth: true
      mail.transport.protocol: smtp
      mail.smtp.starttls.enable: true
      mail.debug: true
      mail.smtp.connectiontimeout: 10000
      
      
---
spring:
  profiles: dev
projeto:
  plataformaUi: http://localhost:4200
  plataformaApi: http://localhost:9998
  app:
    ip: localhost
  db:
    url: jdbc:mysql://localhost:3306/gestao
    database: gestao
    usuario: root
    senha: 123456789
  revendaVeiculosUrl: http://localhost:8080
  
---
spring:
  profiles: prod
projeto:
  plataformaUi:  https://www.inovvet.com.br
  plataformaApi: http://inovvet-accounts:9998
  db:
    url: jdbc:mysql://inovvet-mysql:3306/gestao
    database: gestao
    usuario: root
    senha: 123456789

---
spring:
  profiles: docker
projeto:
  plataformaUi: http://localhost:4200
  plataformaApi: http://localhost:9998
  app:
    ip: localhost
  db:
    url: jdbc:mysql://inovvet-mysql:3306/gestao
    database: gestao
    usuario: root
    senha: 123456789
        

        
    
    