CREATE TABLE IF NOT EXISTS `conta` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(12) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `data_credito` DATE NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE key uk_conta_token(token))
  ENGINE=InnoDB;