CREATE TABLE IF NOT EXISTS `log_handler` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,  
  `url` VARCHAR(255) NULL,
  `erro` text NULL,
  `stacktrace` text  NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE=InnoDB;
  