CREATE TABLE IF NOT EXISTS `permissao_conta` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `perfil_id` TINYINT(1) NOT NULL DEFAULT 0,
  `permissao` VARCHAR(50) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE=InnoDB;