CREATE TABLE IF NOT EXISTS
  `cliente` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loja_id` INT(11) UNSIGNED NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `data_nascimento` DATE, 
  `email` VARCHAR(255) NULL,
  `observacao` VARCHAR(255) NULL,
  `tipo` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Fisica, Juridica' ,
  `sexo` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Masculino, Feminio',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`cpf`))
   ENGINE=InnoDB;