CREATE TABLE IF NOT EXISTS `log` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'INFO, ALERTA, SUCESSO, ERRO',
  `objeto` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'SISTEMA, CONTA, LOJA',
  `mensagem` LONGTEXT NOT NULL,
  `data` DATETIME NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE=InnoDB;