CREATE TABLE IF NOT EXISTS `loja` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta_id` INT(11)UNSIGNED NOT NULL,
  `tipo_documento` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 = CPF 1 = CNPJ',
  `documento` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(150) NULL,
  `nome_fantasia` VARCHAR(150) NULL,
  `tipo_loja` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 = Petshop',
  `cep` VARCHAR(45) NULL,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `complemento` VARCHAR(150) NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `cidade_codigo` INT(11) UNSIGNED NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE=InnoDB;
  