server:
  port: 9997
  
  
logging:
  level:
    org.springframework.web: DEBUG 
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql:  DEBUG
  
spring:
  datasource:
    url: ${projeto.db.url}?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${projeto.db.usuario}
    password: ${projeto.db.senha}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      idle-timeout: 600000 
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
        
---
spring:
  profiles: dev
projeto:
  plataformaUi: http://localhost:4200
  plataformaApi: http://localhost:9998
  cepApi: https://viacep.com.br/ws/{CEP}/json
  receitaws:
    uri: https://www.receitaws.com.br/v1/cnpj
    token: ????????????????????
  db:
    url: jdbc:mysql://localhost:3306/unico
    database: unico
    usuario: root
    senha: 123456789
  
---
spring:
  profiles: prod
projeto:
  plataformaUi: http://www.inovvet.com.br
  plataformaApi: http://inovvet-accounts
  cepApi: https://viacep.com.br/ws/{CEP}/json
  receitaws:
    uri: https://www.receitaws.com.br/v1/cnpj
    token: ????????????????????
  db:
    url: jdbc:mysql://inovvet-mysql:3306/unico
    database: unico
    usuario: root
    senha: 123456789
  
---
spring:
  profiles: docker
projeto:
  plataformaUi: http://localhost:4200
  plataformaApi: http://localhost:9998
  cepApi: https://viacep.com.br/ws/{CEP}/json
  receitaws:
    uri: https://www.receitaws.com.br/v1/cnpj
    token: ????????????????????
  db:
    url: jdbc:mysql://inovvet-mysql:3306/unico
    database: unico
    usuario: root
    senha: 123456789
  
  



